# -*- coding: utf-8 -*-
{
    "name": "CRM Extended",
    "version": "19.0.3.25.0",
    "author": "Jhuliana Delgado",
    "maintainer": "Jhuliana Delgado",
    "website": "",
    "category": "Sales/CRM",
    "summary": "CRM CreArt 3DP: planificación, inventario, costos, dashboard y automatización por etapa.",
    "depends": [
        "base", "web", "crm", "sale_crm", "product", "stock", "project", "calendar",
        "mierp_gantt",
        "base_geolocalize", "maintenance",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/crm_extended_data.xml",
        "data/creart_3dp_data.xml",
        "data/creart_crm_tags_data.xml",
        "data/creart_lost_reasons_data.xml",
        "data/creart_activity_types_data.xml",
        "data/creart_calendar_event_types_data.xml",
        "data/creart_gantt_data.xml",
        "data/creart_cron_data.xml",
        "views/crm_extended_view.xml",
        "views/crm_print_finance_view.xml",
        "views/crm_planning_view.xml",
        "views/crm_planning_gantt_view.xml",
        "views/crm_materials_view.xml",
        "views/crm_creart_dashboard.xml",
        "views/print_cost_config_view.xml",
        "views/creart_calendar_views.xml",
        "views/crm_creart_menus.xml",
        "views/crm_lost_reason_views.xml",
        "views/mail_activity_type_views.xml",
        "views/creart_chatter_note_views.xml",
        "views/creart_config_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "crm_extended_3D/static/src/scss/crm_quick_create_fix.scss",
            "crm_extended_3D/static/src/scss/creart_calendar_colors.scss",
            "crm_extended_3D/static/src/chatter/creart_chatter_patch.js",
            "crm_extended_3D/static/src/chatter/creart_chatter_patch.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
    "post_init_hook": "post_init_hook",
}
